export const CONVERSATIONS_FETCH_START = 'CONVERSATIONS_FETCH_START';
export const CONVERSATIONS_FETCH_SUCCESS = 'CONVERSATIONS_FETCH_SUCCESS';
export const CONVERSATIONS_FETCH_FAILURE = 'CONVERSATIONS_FETCH_FAILURE';
export const CONVERSATION_SELECT = 'CONVERSATION_SELECT';
export const CONVERSATION_DESELECT = 'CONVERSATION_DESELECT';
export const CONVERSATION_MARK_AS_READ = 'CONVERSATION_MARK_AS_READ';
